# This file was generated by GoReleaser. DO NOT EDIT.
cask "hop" do
  version "2.3.0"

  on_macos do
    on_intel do
      sha256 "e50f24edf4fb1203268bd875195d119099d04ace01bbc705cc4abe9d0d65283f"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b05a21b9c353862ea7921eb6be18ab2a5500a3a8f6cacd8067210c2d67004969"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b6c0b6e01b0f15fddfec22ff5c614acbd73fb1df04f503ec2d0962f2b2839b1"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7665ac1b9615dc71757844e602ed39d7c0427b3220a3895b35c3e77838534c62"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hop"
  desc "A fast, AI-agnostic project switcher for your terminal."
  homepage "https://github.com/philippe-desplats/hop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hop"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To finish setting up hop, run the guided first-run setup:
      hop setup
    It detects your project folders, editor and AI assistant, then prints the
    one line to add to your shell config (~/.zshrc, ~/.bashrc or fish).
  EOS
end
