# This file was generated by GoReleaser. DO NOT EDIT.
cask "hop" do
  version "2.5.1"

  on_macos do
    on_intel do
      sha256 "1b4d9bbe883e522cf70db48b46ab7e043eebd1fdda090dd794c8c57ae1e19cae"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "041541259cee9a1175604e60e275608a72d0e4c6f101cffdf0364877e5d1ea16"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8c37b23fbe85fa85ae848d02411811fd52d4e2681890d7f0040a03e036609ed2"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0bb87d87ca8073b3c3df3b8980ede03986760ba24a7b38cd4443534dd0151a4b"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hop"
  desc "A fast, AI-agnostic project switcher for your terminal."
  homepage "https://github.com/philippe-desplats/hop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hop"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To finish setting up hop, run the guided first-run setup:
      hop setup
    It detects your project folders, editor and AI assistant, then prints the
    one line to add to your shell config (~/.zshrc, ~/.bashrc or fish).
  EOS
end
