# This file was generated by GoReleaser. DO NOT EDIT.
cask "hop" do
  version "2.1.1"

  on_macos do
    on_intel do
      sha256 "bf4a9a676d1e3f51572dc4ab9b65ec8d6361647e6d45d4285d1e9a841b5b2280"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e591e754388afe5a856cec44866f516a00a4a3f54ff86b9d81de0a4205cef70c"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18e6b29cb20fd572ab24e586adbe476dff784f9baab5fa6a76747c715bf6a385"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "061b5465accdf8486582f1f8485aa2ff08c959c4d573ede4c40ddc37ba02f8c1"
      url "https://github.com/philippe-desplats/hop/releases/download/v#{version}/hop_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hop"
  desc "A fast, AI-agnostic project switcher for your terminal."
  homepage "https://github.com/philippe-desplats/hop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hop"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To finish setting up hop, run the guided first-run setup:
      hop setup
    It detects your project folders, editor and AI assistant, then prints the
    one line to add to your shell config (~/.zshrc, ~/.bashrc or fish).
  EOS
end
